POST http://localhost:5000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlckBleGFtcGxlLmNvbSIsImlkIjoxLCJpYXQiOjE2OTYwNDY3NDV9.scVo8BGTGx5uOGFzv9b_SfHa5JvebYCQD3XFW1B7WTE

{
  "author": "Miguel Grinberg",
  "url": "https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-ii-templates",
  "title": "The Flask Mega-Tutorial Part II: Templates",
  "published": 2023
}
